/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 dead_plant.gltf 
Author: pamoan10 (https://sketchfab.com/pamoan10)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/dead-plant-9e38cb9d4ddb470391796a9525d56b5b
Title: Dead plant
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/dead_plant/dead_plant.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder002_default_0.geometry} material={materials['default']} rotation={[-Math.PI, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/dead_plant.gltf')
