/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 tomato_plant_diagram.gltf 
Author: diana.ketskalo (https://sketchfab.com/diana.ketskalo)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/tomato-plant-diagram-31558a51bffc43e2851a6f3957883946
Title: Tomato Plant Diagram
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/tomato_plant_diagram/tomato_plant_diagram.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.material_0} />
    </group>
  )
}

useGLTF.preload('/tomato_plant_diagram.gltf')
