/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 tomato_plant.gltf 
Author: ellievaskali (https://sketchfab.com/ellievaskali)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tomato-plant-60d3cb49e21d46cf81f1e7e295793102
Title: Tomato plant
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/tomato_plant/tomato_plant.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_5.geometry} material={materials.Tomato_Plant_924576020} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/tomato_plant.gltf')
